[Camera]
; 相机类型: folder mvs vdo video
type=folder

[Detector]
; 检测器类型: edgesin crack wholedec middledec flysilk
type=edgesin

[Database]
; 是否存库: 1=是 0=否
saveDb=0
[Scoilid]
; 检测位置: 1-上表面WS 2-上表面ds 3-下表面ds 4-+下表面ds
scoilid=1

[DbConnection]
; 数据库连接信息
ip=127.0.0.1
port=3306
user=root
password=daitto
dbName=surface

[Alert]
; 是否实时报警: 1=是 0=否
sendAlert=1
